#server config
server:
  port: 8001

# database config
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: C##MATCAT
    password: MATCAT
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
  # file upload config
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      location: C:/semi/MATCAT
  mail:
    host: smtp.naver.com
    port: 465
    username: dlwnstjr0310@naver.com
    password: "ㅎㅎ"
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 713705979942-b9kvhnt674ng96crpje5eeppdnfvv77o.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
          naver:
            client-id: mh7aVWx7LhWbpchs78VG
            client-secret: Y2BqKfoABl
            client-name: Naver
            redirect-uri: http://localhost:8001/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
          kakao:
            client-id: 02084e3311b089d48f1df5a390f3a8aa
            client-secret: NdEhgZeSsnPba1kVKYrYFfv4juzqAyYd
            client-name: KaKao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8001/login/oauth2/code/kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            userInfo-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  http:
    converters:
      preferred-json-mapper: gson
# image upload directory config
image:
  image-dir: src/main/resources/upload/
# mybatis config
mybatis:
  mapper-locations: mappers/**/*.xml

