package com.greedy.matcat.order.dto;

public class RefundDTO {

	
//	REF_CODE	VARCHAR2(20 BYTE)
//	PAY_CODE	NUMBER(10,0)
//	REF_DATE	DATE
//	REF_AMOUNT	NUMBER(8,0)
//	REF_REASON	VARCHAR2(200 BYTE)
//	REF_DETAIL_REASON	VARCHAR2(4000 BYTE)
//	REF_COMPLETION_DATE	DATE
//	STATUS_CODE	VARCHAR2(10 BYTE)
	
	private String refCode;
//	private 
}
